### ISSUE TITLE
emails are still in english even though locale is set to `fa`

### ISSUE THREAD

**Issue by hadifarnoud** [helpyio/helpy#272] opened 2016-08-05 08:24 UTC
ticket reply emails are still in English even though I changed default locale to Persian. 
<img width="482" alt="screen shot 1395-05-11 at 9 43 39 am" src="https://cloud.githubusercontent.com/assets/589808/17284055/8987f02e-57cc-11e6-8708-a376e34f37a9.png">

**Comment by scott** [comment] 2016-08-05 21:13
Seems like a bug, I will look into it.  Obviously this should not be the case.

**Comment by scott** [comment] 2016-08-06 03:03
I couldn't reproduce this yet, can you tell me which languages are turned on (I assume just `fa`) and which you have selected from the default locale dropdown in the settings panel.  Also if you could include the `I18n.available_locales` line from `production.rb`.

Helpy does a little algorithm to try to remember your locale when you create a discussion in the first place- so if you had your browser set to `en` when you created the issue, it will use this for the mailers, regardless of what language you actually type in.  This is even true if you have manually browsed to the `/fa/whatever` because the source of truth that Helpy uses is the browser locale setting.

**Comment by hadifarnoud** [comment] 2016-08-06 10:17
`config.i18n.available_locales = [:en, :es, :de, :fr, :et, :ca, :ru, :ja, :hi, 'zh-cn', 'zh-tw', 'pt', :nl, 'tr', 'pt-br', :fa]`
my browser locale is English. is there anyway to override this? if the user is inside /fa, that should be the default language. Most of us use English as default locale on our browser.

**Comment by hadifarnoud** [comment] 2016-09-03 15:04
I couldn't find a solution to this one yet.

**Comment by CGA1123** [comment] 2016-09-03 15:27
It seems that the mailers do not explicitly set the locale?

[This stackoverflow question](https://stackoverflow.com/questions/9311956/devise-and-localized-own-mail-template#9313799) might be of interest.

**Comment by hadifarnoud** [comment] 2016-09-04 07:49
ok, I don't want to edit core codes myself. can you fix this or send a PR so I can test it?

**Comment by hadifarnoud** [comment] 2016-10-01 08:39
any update on this bug? we are blocked using Helpy just because of this issue

**Comment by CGA1123** [comment] 2016-10-01 09:00
@hadifarnoud I'll have another look at this.

**Comment by CGA1123** [comment] 2016-10-01 09:35
@scott I'm thinking this may be happening due to the way that the `locale` [field is set in the `Topic` model. ](https://github.com/helpyio/helpy/blob/master/app/models/topic.rb#L177)

I think that `I18n.locale` will get `default_locale` instead of `@locale` due to the fact that it's being set in the model.

Is that a possibility?

**Comment by hadifarnoud** [comment] 2016-10-01 09:47
@CGA1123 it uses default browser settings for that. Since we only have one locale set up, it shouldn't use English even if browser locale is English. We only have Persian enabled now

**Comment by CGA1123** [comment] 2016-10-01 10:05
@hadifarnoud I just tested now with locale set to `fa`, seems to work fine.

**Comment by hadifarnoud** [comment] 2016-10-01 11:14
the issue is, most of users keep their locale set to English. We don't have English locale on our Helpy setup. it shouldn't use `en` then

**Comment by CGA1123** [comment] 2016-10-01 13:21
How do the users set their locale to english if it isn't available?

Selecting only farsi and setting farsi as the default in `/admin/settings` internationalisation, removes the locale changing feature from the header for me.

**Comment by hadifarnoud** [comment] 2016-10-01 14:11
Let me explain in details:

Locale in Helpy is Farsi only. there is no option to change it as we only have Farsi enabled.

However, if user browser language is set to English, the emails will be sent to him in English. It shouldn't. we have one locale in Helpy and every email should be in that locale only.

Does it make sense?

**Comment by CGA1123** [comment] 2016-10-01 15:50
Yes, however my browser locale is set to english as well, and the emails go through as farsi (For emails sent by the `TopicMailer` anyways.)

Other mailers don't seem to explicitly set `@locale` in their methods, which means some emails might revert back to english given that the default locale set in `production.rb` is set to`:en`.

One fix might be to change `config.i18n.default_locale` to `:fa` in `config/environments/*.rb` if you haven't done so yet.

Otherwise, the `TopicMailer` sets the locale for email from the locale which the topic was created in.

Other mailers such as the `NotificationMailer` don't appear to set the locale, unless it is done elsewhere, which isn't evident from looking at the source.

I'd be happy to send a PR to add that to those mailers missing that feature, unless @scott has it set up do that elsewhere.

However, for the example you have given, which is sent by `TopicMailer#new_ticket`, the translation should work.

**Comment by hadifarnoud** [comment] 2016-10-02 14:07
nope, still have issues. another weird thing that happened is new ticket form doesn't work. I only changed default locale to `fa`.

![screen shot 1395-07-11 at 3 47 45 pm](https://cloud.githubusercontent.com/assets/589808/19021095/b500d9f2-88c6-11e6-814b-7e9ee392844f.png)

notice the english line ` A new private customer message...` line?
![screen shot 1395-07-11 at 3 58 14 pm](https://cloud.githubusercontent.com/assets/589808/19021096/b76d66a6-88c6-11e6-8e3b-7fb684d7cab1.png)

**Comment by hadifarnoud** [comment] 2016-10-02 14:58
correction: the english string was due to missing translation. I sent a pull request to update it.

the only issue seems to be the emails text direction, which should be RTL but isn't

**Comment by CGA1123** [comment] 2016-10-02 17:09
So all the other issues are fixed now? 

Apart from the text not being RTL?

**Comment by hadifarnoud** [comment] 2016-10-03 08:08
there is a new issue ever since I updated to new version. I can't create new tickets from http://support.kamva.ir/fa/topics/new

it just goes back to new topic page and nothing happens.

and RTL issue for emails.

I'm running exact version of this: https://github.com/KamvaHQ/helpy

**Comment by CGA1123** [comment] 2016-10-03 15:08
It seems some of the email views should have RTL support set up.

Emails sent by`TopicMailer` & `UserMailer` should be displaying text correctly, can you confirm?

**Comment by hadifarnoud** [comment] 2016-10-03 16:13
if ‍`TopicMailer` is for new topics notification and replies, no it's not fixed. I still get them as LTR.
<img width="820" alt="screen shot 1395-07-12 at 7 36 15 pm" src="https://cloud.githubusercontent.com/assets/589808/19044520/909afdf0-89a1-11e6-87a9-fbb1dded8e7b.png">
Should I create a new ticket to test it or just replying to one would suffice?

If `UserMailer` is for forgot password etc, then yes these emails are in RTL.
<img width="1210" alt="screen shot 1395-07-12 at 7 42 19 pm" src="https://cloud.githubusercontent.com/assets/589808/19044513/862d067e-89a1-11e6-978c-97c741d6a921.png">

**Comment by scott** [comment] 2016-10-03 16:24
The forgot password is generated by `devise_mailer` which is a separate concern.  The `topic_mailer` handles the topic email to a user to let them know there is a new reply.  The `user_mailer` is sent to users upon their creation to let them know that an account was generated for them.

So the way to test `user_mailer` is by submitting a new ticket via email or form with a never before registered email address.

Note- if you are running in dev mode, I highly recommend using `mailcatcher` to help debug- simply open a new terminal window and type `mailcatcher` and then open the referenced URL...  Helpy should already use the correct SMTP but if not you can configure it.

**Comment by CGA1123** [comment] 2016-10-03 17:48
@scott mailcatcher is sweet!

**Closed** 2016-10-05 13:30 UTC
Labels: i18n
