### ISSUE TITLE
I18n files organization

### ISSUE THREAD

**Issue by lidimayra** [helpyio/helpy#332] opened 2016-09-19 01:35 UTC
While working in bug #66, I noticed that I18n files are divided in such way to provide one file per locale.

It's a good practice to have these files structure similar to the structure of the project.
([reference here](http://guides.rubyonrails.org/i18n.html#organization-of-locale-files))

Any interests in this? If so, I would be glad to submit a pull request to help :relaxed:

**Comment by scott** [comment] 2016-09-19 22:08
Let me me think about this one.  I agree there may be a benefit of having the structure similar to the app, however we have had a few translations from non technical users who can just take the .yml file and work down it and send back as a text file.  I am concerned breaking it up as the guide suggests could make it really difficult for these translators.

What are your thoughts about this?

**Comment by scott** [comment] 2016-09-19 22:12
Also related to #243

**Comment by lidimayra** [comment] 2016-09-20 03:28
I see... when thinking about the project itself I'm definitely inclined to go for the reorganization.

But you've got a good point over there. When it comes to non technical contributors, current format is much more friendly. :)

**Comment by CGA1123** [comment] 2016-09-20 08:24
I think setting up where it is more modular makes more sense. 

For non-technical people, an in-depth guide could be made up in the docs, or they could submit a file in the old 'format' and then someone else could just split it up, or even better, a script could probably be written to split the file up automatically.

**Comment by scott** [comment] 2016-10-19 20:49
The problem is with the rapid growth in number of i18n strings, keeping a guide up to date would be a challenge.  For the time being I am closing this.

**Closed by scott** 2016-10-19 20:49 UTC
