### ISSUE TITLE
500 Internal Server Error in /users/sign_in page

### ISSUE THREAD

**Issue by bnymn** [helpyio/helpy#830] opened 2018-06-21 18:07 UTC
I am getting 500 Internal Server error when I try to visit **/users/sign_in** page. The strange part is that I am not seeing any other error message on the console. Here is the output on the console.

![screenshot from 2018-06-21 15-05-25](https://user-images.githubusercontent.com/3506402/41737082-99f2a258-7564-11e8-9efc-bee80cffb7fc.png)

### How to reproduce

1. Download Helpy version 1.2.1.
2. Run `bundle install`
3. Configure `database.yml`
4. Run `bin/rake db:migrate`
5. Run `bin/rails s`
6. Go to http://localhost:3000/users/sign_in.

**Comment by bnymn** [comment] 2018-06-21 22:55
I cannot reproduce this problem in version **1.2.0**.

**Comment by scott** [comment] 2018-06-23 20:45
That seems strange, I can verify that it works fine. Did you remember to seed the database, by the way?  I doubt that would cause this error, but there are some settings there.

**Comment by lidimayra** [comment] 2018-07-09 04:02
@bnymn you are not being able to see the error message because `config_all_requests_to_local` is set to _false_ in this file: https://github.com/helpyio/helpy/blob/e2fd7ef38f00e8a8da4b29a62a1b3f920ed644d0/config/environments/development.rb#L15

Try to change its value to `true` and you'll get full message instead of generic _Internal Server Error_ page being rendered.

Actually, I would highly suggest to helpy maintainers to turn this value to _true_ in development environment, as this is the most common practice in Rails projects.

Usually, we only want 500 and 404 error pages to be rendered in production mode.
For developers, we rather having a complete log and friendly messages in order to investigate possible problems. :smiley_cat:

**Comment by lidimayra** [comment] 2018-07-09 18:43
@bnymn I might have just bumped into the same bug as you.

Which Ruby version are you using?

Reproducing this scenario in my machine, noted sign in page crashing when using Ruby 2.5.0.

That's because Helpy uses Devise 3.5.6:
https://github.com/helpyio/helpy/blob/e2fd7ef38f00e8a8da4b29a62a1b3f920ed644d0/Gemfile.lock#L166

After Ruby 2.5. release, this issue came up and it is fixed on Devise 4.4.0 (more specifically, in this PR: https://github.com/plataformatec/devise/pull/4668)

When running Helpy inside Docker, this error cannot be found, because Helpy Dockerfile uses Ruby 2.4.

Some possibilities:
  - Use another Ruby version in your machine
  - Run helpy app inside Docker
  - Update Devise version for Helpy

**Comment by scott** [comment] 2019-03-22 19:21
Helpy has been upgraded to Devise 4.6.1 finally.  Closing.

**Closed by scott** 2019-03-22 19:21 UTC
